### ISSUE TITLE
TOPIC: Maquetación de TumiLanding

### ISSUE THREAD

**Issue by reinamercedes** [controlinn/dp6WebTumiLanding#2]
**Overview**
Tareas necesarias para la maquetacion del landing de TumiPOS.

**Issues**
 - [x] #3 Crear componentes fijos (header, footer)
 - [x] #4 Crear landing Funciones
 - [x] #5 Crear landing Dispositivos
 - [x] #6 Crear landing Galería
 - [x] #7 Crear landing Contáctanos
